<?php
/*
 * @file
 * A module that allows automatic creation of posts for Twitter, Facebook,
 * and Google+ after content is created on your site.
 * Each network is controlled by a submodule.
 */

 /*
 * Implements hook_help().
 */
function social_syndication_help($path, $arg) {
  $help = '';
  switch ($path) {
    case 'node/add/page':
      return t('Use the Social Syndication tab below to automatically post this content to your social networks.');
      break;
    default:
      return $help;
      break;
  }
}

/*
 * Implements hook_menu().
 */
function social_syndication_menu() {
  // Module settings.
  $items['admin/config/services/social_syndication'] = array(
    'title' => 'Social Syndication Overview',
    'description' => 'Configure settings for posting to social networks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_syndication_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/services/social_syndication/social'] = array(
    'title' => 'Overview',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/services/social_syndication/twitter'] = array(
    'title' => 'Enable Twitter Posting',
    'description' => 'Authorize a Twitter account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items['admin/config/services/social_syndication/bitly'] = array(
    'title' => 'Connect to Bitly',
    'description' => 'Connect your bitly account for shortening URLs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bitly_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_LOCAL_TASK,
    'weight' => 15,
    );
  return $items;
}

/*
 * Implements hook_form_alter().
 *
 * Add custom tab for setting up social posts
 */
function social_syndication_form_alter(&$form, $form_state, $form_id) {
  // Only include on node add/edit forms
  // TODO create settings page and check for content type
  if (!empty($form['#node_edit_form'])) {
    $form['social_syndication'] = array(
      '#type' => 'fieldset',
      '#title' => t('Social Syndication'),
      '#collapsable' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
      '#attached' => array(
        'js' => array(
          'vertical-tabs' => drupal_get_path('module', 'social_syndication') . '/js/social_syndication.js',
        ),
      ),
      '#tree' => TRUE,
      '#weight' => 10,
    );

    // This checkbox is used to show or hide the custom settings form using
    // javascript (altering states of a container defined later).
    // TODO Check if twitter_syndication is enabled
    $form['social_syndication']['tweet_post'] = array(
      '#type' => 'checkbox',
      '#title' => t('Post to Twitter'),
      '#default_value' => FALSE, // TODO create settings and get value from settings.
    );

    // This container will be used to store the whole form for our custom
    // settings. This way, showing/hidding the form using javascript is easier,
    // as only one element should be set visible.
    $form['social_syndication']['social_syndication_container'] = array(
      '#type' => 'container',
      '#parents' => array('social_syndication'),
      '#states' => array(
        'invisible' => array(
          // If the checkbox is not enabled, show the container.
          'input[name="social_syndication[tweet_post]"]' => array('checked' => FALSE),
        ),
      ),
    );
  }
}