<?php
/*
 * @file
 * A module that allows automatic creation of posts for Twitter, Facebook,
 * and Google+ after content is created on your site.
 * Each network is controlled by a submodule.
 */

 /*
 * Implements hook_help().
 */
function social_syndication_help($path, $arg) {
  $help = '';
  switch ($path) {
    case 'node/add/page':
      return t('Use the Social Syndication tab below to automatically post this content to your social networks.');
      break;
    case 'admin/help#social_syndication':
      return _twitter_syndication_help_page();
      break;
    default:
      return $help;
      break;
  }
}

/*
 * Implements hook_menu().
 */
function social_syndication_menu() {
  // Module settings.
  $items['admin/config/services/social_syndication'] = array(
    'title' => 'Social Syndication Overview',
    'description' => 'Configure settings for posting to social networks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_syndication_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/services/social_syndication/social'] = array(
    'title' => 'Overview',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/services/social_syndication/twitter'] = array(
    'title' => 'Enable Twitter Posting',
    'description' => 'Authorize a Twitter account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items['admin/config/services/social_syndication/bitly'] = array(
    'title' => 'Connect to Bitly',
    'description' => 'Connect your bitly account for shortening URLs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bitly_admin_profile_form'),
    'file' => 'social_syndication.admin.inc',
    'file path' => drupal_get_path('module', 'social_syndication'),
    'access callback' => TRUE, //TODO create permissions
    'type' => MENU_LOCAL_TASK,
    'weight' => 15,
    );
  return $items;
}

/**
 * Implements hook_permission().
 */
function social_syndication_permission() {
  return array(
    'post content to social media' => array(
    'title' => t('Post Content to Social Media'),
    ),
  );
}

/*
 * Implements hook_form_alter().
 *
 * Add custom tab for setting up social posts
 */
function social_syndication_form_alter(&$form, $form_state, $form_id) {
  if ( module_exists('twitter_syndication') && !empty($form['#node_edit_form']) ) {
    $nodetype = $form['#node']->type;
    $nodestopost = variable_get('ss_node_types');

    //Make sure this node type has been chosen in settings
    if ($nodestopost[$nodetype] === $nodetype) {
      //Add a tab  to hold all the social form elements
      $form['social_syndication'] = array(
      '#type' => 'fieldset',
      '#title' => t('Social Syndication'),
      '#collapsable' => TRUE,
      '#collapsed' => FALSE,
      '#group' => 'additional_settings',
      '#attached' => array(
        'js' => array(
          'vertical-tabs' => drupal_get_path('module', 'social_syndication') . '/js/social_syndication.js',
        ),
      ),
      '#tree' => TRUE,
      '#weight' => -20,
      );

      // This checkbox is used to show or hide the custom settings form using
      // javascript (altering states of a container defined later).
      // TODO Check if twitter_syndication is enabled
      $form['social_syndication']['tweet_post'] = array(
        '#type' => 'checkbox',
        '#title' => t('Post to Twitter'),
        '#default_value' => FALSE, // TODO create settings and get value from settings.
      );

      // This container will be used to store the whole form for our custom
      // settings. This way, showing/hidding the form using javascript is easier,
      // as only one element should be set visible.
      $form['social_syndication']['social_syndication_container'] = array(
        '#type' => 'container',
        '#parents' => array('social_syndication'),
        '#states' => array(
          'invisible' => array(
            // If the checkbox is not enabled, show the container.
            'input[name="social_syndication[tweet_post]"]' => array('checked' => FALSE),
          ),
        ),
      );
    }// end inner if
  }//end outter if
}

/*
 * Help page for the Social Syndication module
 */
function _twitter_syndication_help_page() {
  $output = '';
  $output .= '<h3>' . t('About') . '</h3>';
  $output .= '<p>' . t('Social Syndication is* a suite of modules that allow you to automatically post your Drupal content to the three major social networks: Twitter, Facebook and Google Plus') . '</p>';
  $output .= '<p>' . t('It works by adding a Social tab to the node/edit form on the content types you select for posting. If the Token module is enabled, you may use Tokens to fill in placeholder text for a tweet, such as the title, URL or author\'s Twitter username. The module can make use of the Shorten module for URL shortening if it is installed, or be connected to your Bitly account.') . '</p>';
  $output .= '<p>' . t('Check out the configuration page at /admin/config/services/social_syndication') . '</p>';
  $output .= '<p>' . t('*Facebook and Google Plus to be added at a later date') . '</p>';
  return $output;
}