<?php
/*
 * @file
 * Automatically post your content to Twitter
 */

 /*
 * Implements hook_node_presave().
 */
function twitter_syndication_node_presave($node) {
  dpm($node);
}

function twitter_syndication_help($path, $arg) {
  $node = node_load($arg[1]);
  dpm($node);
}

/*
 * Implements hook_form_alter().
 *
 * Add settings for posting to Twitter
 */
function twitter_syndication_form_alter(&$form, $form_state, $form_id) {
  // Only include on node add/edit forms
  // TODO create settings page and check for content type
  if (!empty($form['#node_edit_form'])) {

    // Just to prove I can put more form elements from a different module
    $form['social_syndication']['test_checkbox'] = array(
      '#type' => 'checkbox',
      '#title' => t('Another checkbox'),
      '#default_value' => FALSE,
    );

    $entities = entity_get_info();
    $token_types = array();

    // Scan through the list of entities for supported token entities.
    foreach ($entities as $entity => $info) {
      $object_callback = "_token_example_get_{$entity}";
      if (function_exists($object_callback) && $objects = $object_callback()) {
        $form[$entity] = array(
          '#type' => 'select',
          '#title' => $info['label'],
          '#options' => array(0 => t('Not selected')) + $objects,
          '#default_value' => isset($form_state['storage'][$entity]) ? $form_state['storage'][$entity] : 0,
          '#access' => !empty($objects),
        );

        // Build a list of supported token types based on the available entites.
        if ($form[$entity]['#access']) {
          $token_types[$entity] = !empty($info['token type']) ? $info['token type'] : $entity;
        }
      }
    }

    // Display the results of tokenized text.
    if (!empty($form_state['storage']['social_syndication']['social_syndication_container']['twitter_message'])) {
      $form['social_syndication']['social_syndication_container']['twitter_message'] = $form_state['storage']['social_syndication']['social_syndication_container']['twitter_message'];

      $data = array();
      foreach ($entities as $entity => $info) {
        if (!empty($form_state['storage'][$entity])) {
          $objects = entity_load($entity, array($form_state['storage'][$entity]));
          if ($objects) {
            $data[$token_types[$entity]] = reset($objects);
          }
        }
      }
      // Display the tokenized text.
      $form['text_tokenized'] = array(
        '#type' => 'item',
        '#title' => t('Result'),
        '#markup' => token_replace($form_state['storage']['social_syndication']['social_syndication_container']['twitter_message'], $data),
      );
    }

    if (module_exists('token')) {
      $form['social_syndication']['social_syndication_container']['token_tree'] = array(
        '#theme' => 'token_tree',
        '#token_types' => $token_types,
      );
    }
    else {
      $form['social_syndication']['social_syndication_container']['token_tree'] = array(
        '#markup' => '<p>' . t('Enable the <a href="@drupal-token">Token module</a> to view the available token browser.', array('@drupal-token' => 'http://drupal.org/project/token')) . '</p>',
      );
    }


    dpm($form, 'form');
    dpm($form_state, 'form state');
  }
}